### ISSUE TITLE
Question: How to display 12:30 AM or 12:30 PM in a 12 hour format?

### ISSUE THREAD

**Issue by parveenkumardeeva** [MarcinOrlowski/DateTimeTemplate#10]
Hello Dear,

I was trying to display 12:30 AM or 12:30 PM in a 12 hour format but your library is displaying only 00:30 AM or 00:30 PM. Is it possible to display my type of format into your library or Am I doing something wrong? 

My Current format is "%d% %MM% %y%, %kk%:%ii% %AA%"

**Comment by MarcinOrlowski** [comment]
This was a bug in the library, which I just fixed in v1.2.4 (release now). Thanks for reporting.
